server:
  port: ${SERVER_PORT:8087}

spring:
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:mysql://mysql-notification:3306/banquito_notification_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Guayaquil}
    username: ${NOTIFICATION_DB_USERNAME:root}
    password: ${NOTIFICATION_DB_PASSWORD:BanQuitoRoot2026!}
  mail:
    host: ${SMTP_HOST:mailpit}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:false}
          starttls:
            enable: ${SMTP_STARTTLS_ENABLE:false}

banquito:
  internal:
    service-key: ${INTERNAL_SERVICE_KEY:BanQuitoInternalServiceKey2026ChangeMe}
  security:
    jwt:
      issuer: ${JWT_ISSUER:banquito-identity-access}
      secret: ${JWT_SECRET:BanQuitoIdentityJwtSecretKeyForDevelopmentOnlyChangeMe2026}
  grpc:
    server:
      port: ${NOTIFICATION_GRPC_PORT:9097}
  notification:
    delivery:
      mode: ${NOTIFICATION_DELIVERY_MODE:SIMULATED}
      provider: ${NOTIFICATION_PROVIDER:SMTP}
      from: ${SMTP_FROM:no-reply@banquito.com}
      reply-to: ${SMTP_REPLY_TO:}
