-- ============================================================================
-- BANCO BANQUITO V2 - NOTIFICATION SERVICE
-- Modelo fisico MySQL 8.4 LTS
-- Base: banquito_notification_db
-- Proposito: plantillas, solicitudes, intentos, preferencias, configuracion de
-- canales y auditoria de notificaciones para Core, Switch e Identity.
-- ============================================================================
CREATE DATABASE IF NOT EXISTS banquito_notification_db
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE banquito_notification_db;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS AUDITORIA_NOTIFICATION_EVENTO;
DROP TABLE IF EXISTS NOTIFICATION_DELIVERY_ATTEMPT;
DROP TABLE IF EXISTS NOTIFICATION_REQUEST;
DROP TABLE IF EXISTS NOTIFICATION_PREFERENCE;
DROP TABLE IF EXISTS NOTIFICATION_TEMPLATE;
DROP TABLE IF EXISTS NOTIFICATION_CHANNEL_CONFIG;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE NOTIFICATION_CHANNEL_CONFIG (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(40) NOT NULL,
  TIPO_CANAL VARCHAR(20) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  CONFIG_JSON JSON NULL COMMENT 'Configuracion no sensible; secretos van fuera de BD o cifrados',
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_NOTIF_CHANNEL PRIMARY KEY (ID),
  CONSTRAINT UK_NOTIF_CHANNEL_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_NOTIF_CHANNEL_TIPO CHECK (TIPO_CANAL IN ('EMAIL','SMS','PUSH','WEBHOOK')),
  CONSTRAINT CK_NOTIF_CHANNEL_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Canales disponibles para notificaciones';

CREATE TABLE NOTIFICATION_TEMPLATE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(80) NOT NULL,
  TIPO_EVENTO VARCHAR(80) NOT NULL,
  TIPO_CANAL VARCHAR(20) NOT NULL,
  ASUNTO_TEMPLATE VARCHAR(250) NULL,
  CUERPO_TEMPLATE TEXT NOT NULL,
  IDIOMA VARCHAR(10) NOT NULL DEFAULT 'es-EC',
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_NOTIF_TEMPLATE PRIMARY KEY (ID),
  CONSTRAINT UK_NOTIF_TEMPLATE_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_NOTIF_TEMPLATE_CANAL CHECK (TIPO_CANAL IN ('EMAIL','SMS','PUSH','WEBHOOK')),
  CONSTRAINT CK_NOTIF_TEMPLATE_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Plantillas de notificacion';

CREATE TABLE NOTIFICATION_PREFERENCE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_ACTOR CHAR(36) NOT NULL COMMENT 'UUID de cliente/usuario/empresa; sin FK cruzada',
  TIPO_ACTOR VARCHAR(20) NOT NULL COMMENT 'CLIENTE, EMPLEADO, EMPRESA, SERVICIO',
  TIPO_EVENTO VARCHAR(80) NOT NULL,
  TIPO_CANAL VARCHAR(20) NOT NULL,
  HABILITADO TINYINT(1) NOT NULL DEFAULT 1,
  DESTINO VARCHAR(180) NULL COMMENT 'Correo/telefono/canal preferido si aplica',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_NOTIF_PREF PRIMARY KEY (ID),
  CONSTRAINT UK_NOTIF_PREF UNIQUE (UUID_ACTOR, TIPO_EVENTO, TIPO_CANAL),
  CONSTRAINT CK_NOTIF_PREF_ACTOR CHECK (TIPO_ACTOR IN ('CLIENTE','EMPLEADO','EMPRESA','SERVICIO')),
  CONSTRAINT CK_NOTIF_PREF_CANAL CHECK (TIPO_CANAL IN ('EMAIL','SMS','PUSH','WEBHOOK'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Preferencias de notificacion por actor';

CREATE TABLE NOTIFICATION_REQUEST (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_NOTIFICACION CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  TIPO_EVENTO VARCHAR(80) NOT NULL,
  ORIGEN_SERVICIO VARCHAR(80) NOT NULL,
  PRIORIDAD VARCHAR(15) NOT NULL DEFAULT 'NORMAL',
  TIPO_CANAL VARCHAR(20) NOT NULL,
  DESTINATARIO VARCHAR(180) NOT NULL,
  DESTINATARIO_NOMBRE VARCHAR(180) NULL,
  TEMPLATE_CODIGO VARCHAR(80) NULL,
  ASUNTO_RENDERIZADO VARCHAR(250) NULL,
  CUERPO_RENDERIZADO MEDIUMTEXT NULL,
  PAYLOAD_JSON JSON NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  UUID_DOCUMENTO_EVIDENCIA CHAR(36) NULL COMMENT 'Documento/evidencia en document-service',
  FECHA_SOLICITUD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ULTIMO_INTENTO DATETIME NULL,
  FECHA_ENVIO DATETIME NULL,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_NOTIF_REQUEST PRIMARY KEY (ID),
  CONSTRAINT UK_NOTIF_REQUEST_UUID UNIQUE (UUID_NOTIFICACION),
  CONSTRAINT CK_NOTIF_REQUEST_PRIORIDAD CHECK (PRIORIDAD IN ('BAJA','NORMAL','ALTA','CRITICA')),
  CONSTRAINT CK_NOTIF_REQUEST_CANAL CHECK (TIPO_CANAL IN ('EMAIL','SMS','PUSH','WEBHOOK')),
  CONSTRAINT CK_NOTIF_REQUEST_ESTADO CHECK (ESTADO IN ('PENDIENTE','ENVIADA','FALLIDA','REINTENTO','CANCELADA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Solicitudes de notificacion';

CREATE TABLE NOTIFICATION_DELIVERY_ATTEMPT (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  NOTIFICATION_REQUEST_ID BIGINT NOT NULL,
  INTENTO_NUMERO INT NOT NULL,
  PROVEEDOR VARCHAR(80) NOT NULL DEFAULT 'SMTP',
  ESTADO VARCHAR(20) NOT NULL,
  CODIGO_RESPUESTA VARCHAR(80) NULL,
  MENSAJE_RESPUESTA VARCHAR(1000) NULL,
  FECHA_INTENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_NOTIF_ATTEMPT PRIMARY KEY (ID),
  CONSTRAINT UK_NOTIF_ATTEMPT UNIQUE (NOTIFICATION_REQUEST_ID, INTENTO_NUMERO),
  CONSTRAINT FK_NOTIF_ATTEMPT_REQ FOREIGN KEY (NOTIFICATION_REQUEST_ID) REFERENCES NOTIFICATION_REQUEST(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_NOTIF_ATTEMPT_ESTADO CHECK (ESTADO IN ('ENVIADA','FALLIDA','TIMEOUT','RECHAZADA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Intentos de envio de notificacion';

CREATE TABLE AUDITORIA_NOTIFICATION_EVENTO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  MODULO VARCHAR(60) NOT NULL,
  ACCION VARCHAR(80) NOT NULL,
  ENTIDAD VARCHAR(80) NOT NULL,
  ENTIDAD_ID VARCHAR(80) NULL,
  RESULTADO VARCHAR(15) NOT NULL,
  DETALLE_JSON JSON NULL,
  FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_AUDITORIA_NOTIFICATION PRIMARY KEY (ID),
  CONSTRAINT CK_AUDIT_NOTIF_RESULTADO CHECK (RESULTADO IN ('OK','ERROR','DENEGADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Auditoria local de notification-service';

CREATE INDEX IDX_NOTIF_REQUEST_ESTADO ON NOTIFICATION_REQUEST(ESTADO, FECHA_SOLICITUD);
CREATE INDEX IDX_NOTIF_REQUEST_CORR ON NOTIFICATION_REQUEST(UUID_CORRELACION);
CREATE INDEX IDX_NOTIF_ATTEMPT_REQ ON NOTIFICATION_DELIVERY_ATTEMPT(NOTIFICATION_REQUEST_ID, FECHA_INTENTO);

INSERT INTO NOTIFICATION_CHANNEL_CONFIG (CODIGO,TIPO_CANAL,NOMBRE,CONFIG_JSON) VALUES
('EMAIL_SMTP_PRINCIPAL','EMAIL','SMTP Principal', JSON_OBJECT('provider','SMTP','host','smtp.example.local','port',587));

INSERT INTO NOTIFICATION_TEMPLATE (CODIGO,TIPO_EVENTO,TIPO_CANAL,ASUNTO_TEMPLATE,CUERPO_TEMPLATE) VALUES
('ACCOUNT_CREDITED_EMAIL','ACCOUNT_CREDITED','EMAIL','Acreditacion recibida','Estimado/a {{nombre}}, se acredito {{monto}} en su cuenta {{cuenta}}.'),
('ACCOUNT_DEBITED_EMAIL','ACCOUNT_DEBITED','EMAIL','Debito realizado','Estimado/a {{nombre}}, se debito {{monto}} de su cuenta {{cuenta}}.'),
('PASSWORD_CHANGED_EMAIL','PASSWORD_CHANGED','EMAIL','Cambio de clave realizado','Se realizo un cambio de clave en su usuario {{usuario}}.'),
('PAYMENT_LINE_SUCCESS_EMAIL','PAYMENT_LINE_SUCCESS','EMAIL','Pago recibido','Recibio {{monto}} por concepto {{concepto}} de {{empresa}}.'),
('EOD_COMPLETED_EMAIL','EOD_COMPLETED','EMAIL','Cierre diario exitoso','El proceso EOD {{eod}} finalizo exitosamente.');

-- Extensión cloud-ready / SMTP / eventos adicionales
INSERT IGNORE INTO NOTIFICATION_CHANNEL_CONFIG (CODIGO,TIPO_CANAL,NOMBRE,CONFIG_JSON) VALUES
('EMAIL_SMTP_REAL','EMAIL','SMTP Transaccional', JSON_OBJECT('provider','SMTP','configuration','environment-variables'));

INSERT IGNORE INTO NOTIFICATION_TEMPLATE (CODIGO,TIPO_EVENTO,TIPO_CANAL,ASUNTO_TEMPLATE,CUERPO_TEMPLATE,IDIOMA) VALUES
('TEMPORARY_CREDENTIALS_EMAIL','TEMPORARY_CREDENTIALS','EMAIL','Credenciales temporales Banco BanQuito','Estimado/a {{nombre}}, su usuario es {{usuario}} y su código temporal es {{codigoTemporal}}. Por seguridad, deberá cambiar su contraseña en el primer ingreso.','es-EC'),
('PASSWORD_RESET_CODE_EMAIL','PASSWORD_RESET_CODE','EMAIL','Código de recuperación de contraseña','Estimado/a {{nombre}}, su código para recuperar contraseña es {{codigoTemporal}}. Si usted no solicitó este cambio, comuníquese con Banco BanQuito.','es-EC'),
('TRANSFER_SENT_EMAIL','TRANSFER_SENT','EMAIL','Transferencia enviada','Estimado/a {{nombre}}, se envió una transferencia por {{monto}} desde la cuenta {{cuentaOrigen}} hacia {{cuentaDestino}}.','es-EC'),
('TRANSFER_RECEIVED_EMAIL','TRANSFER_RECEIVED','EMAIL','Transferencia recibida','Estimado/a {{nombre}}, recibió una transferencia por {{monto}} en la cuenta {{cuentaDestino}} desde {{ordenante}}.','es-EC'),
('ACCOUNT_WITHDRAWAL_EMAIL','ACCOUNT_WITHDRAWAL','EMAIL','Retiro realizado','Estimado/a {{nombre}}, se realizó un retiro por {{monto}} de la cuenta {{cuenta}}.','es-EC'),
('ACCOUNT_BLOCKED_EMAIL','ACCOUNT_BLOCKED','EMAIL','Cuenta bloqueada','Estimado/a {{nombre}}, la cuenta {{cuenta}} fue bloqueada por motivo: {{motivo}}.','es-EC'),
('PAYMENT_BATCH_COMPLETED_EMAIL','PAYMENT_BATCH_COMPLETED','EMAIL','Lote de pagos masivos procesado','El lote {{lote}} de la empresa {{empresa}} finalizó. Exitosos: {{exitosos}}, rechazados: {{rechazados}}.','es-EC'),
('PAYMENT_BATCH_REJECTED_EMAIL','PAYMENT_BATCH_REJECTED','EMAIL','Lote de pagos masivos rechazado','El lote {{lote}} de la empresa {{empresa}} fue rechazado. Motivo: {{motivo}}.','es-EC'),
('EOD_FAILED_EMAIL','EOD_FAILED','EMAIL','Cierre diario con error','El proceso EOD {{eod}} finalizó con error. Motivo: {{motivo}}.','es-EC'),
('LOGIN_SUSPICIOUS_EMAIL','LOGIN_SUSPICIOUS','EMAIL','Alerta de seguridad Banco BanQuito','Detectamos un evento de seguridad en el usuario {{usuario}}. Detalle: {{detalle}}.','es-EC');
