DELIMITER $$

DROP PROCEDURE IF EXISTS SP_NOTIFICATION_V3 $$
CREATE PROCEDURE SP_NOTIFICATION_V3()
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'NOTIFICATION_REQUEST'
      AND COLUMN_NAME = 'UUID_EVENTO_ORIGEN'
  ) THEN
    ALTER TABLE NOTIFICATION_REQUEST
      ADD COLUMN UUID_EVENTO_ORIGEN CHAR(36) NULL AFTER UUID_CORRELACION;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'NOTIFICATION_REQUEST'
      AND COLUMN_NAME = 'UUID_ACTOR_DESTINATARIO'
  ) THEN
    ALTER TABLE NOTIFICATION_REQUEST
      ADD COLUMN UUID_ACTOR_DESTINATARIO CHAR(36) NULL AFTER UUID_EVENTO_ORIGEN;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'NOTIFICATION_REQUEST'
      AND INDEX_NAME = 'UK_NOTIF_REQUEST_SOURCE'
  ) THEN
    ALTER TABLE NOTIFICATION_REQUEST
      ADD CONSTRAINT UK_NOTIF_REQUEST_SOURCE
      UNIQUE (UUID_EVENTO_ORIGEN, TIPO_EVENTO, DESTINATARIO);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'NOTIFICATION_REQUEST'
      AND INDEX_NAME = 'IDX_NOTIF_REQUEST_ACTOR'
  ) THEN
    CREATE INDEX IDX_NOTIF_REQUEST_ACTOR
      ON NOTIFICATION_REQUEST(UUID_ACTOR_DESTINATARIO, TIPO_EVENTO);
  END IF;
END $$

CALL SP_NOTIFICATION_V3() $$
DROP PROCEDURE IF EXISTS SP_NOTIFICATION_V3 $$

DELIMITER ;
